{name = 'darknet', label = 'Dark Net', price = 25},
{name = 'bandage', label = 'Bandage', price = 2},
{name = 'binoculars', label = 'Binoculars', price = 10},
{name = 'bulletproof', label = 'Bullet-Proof Vest', price = 300},
{name = 'cleankit', label = 'Cleaning Kit', price = 5},
{name = 'defib', label = 'Defib', price = 600},
{name = 'drill', label = 'Drill', price = 180},
{name = 'firework', label = 'Firework', price = 15},
{name = 'firstaidkit', label = 'First Aid Kit', price = 5},
{name = 'handcuffs', label = 'Handcuffs', price = 27},
{name = 'handcuffkey', label = 'Handcuff Key', price = 5},
{name = 'lockpick', label = 'Lock Pick', price = 20},
{name = 'oxygenmask', label = 'Oxygen Mask', price = 400},
{name = 'repairkit', label = 'Repair Kit', price = 250},
{name = 'tirekit', label = 'Tire Kit', price = 20},
{name = 'vape', label = 'Vape', price = 50},
{name = 'vehgps', label = 'Vehicle GPS', price = 100},
{name = 'weakit', label = 'Weapon Kit', price = 75},

-- Simple Ammo
{name = 'boxbig', label = 'Ammo Box Big', price = 60},
{name = 'boxsmall', label = 'Ammo Box Small', price = 25},

-- Advanced Ammo
{name = 'boxpistol', label = 'Ammo Box Pistol', price = 14},
{name = 'boxsmg', label = 'Ammo Box SMG', price = 14},
{name = 'boxshot', label = 'Ammo Box Shotgun', price = 9},
{name = 'boxrifle', label = 'Ammo Box Rifle', price = 12},
{name = 'boxmg', label = 'Ammo Box MG', price = 24},
{name = 'boxsniper', label = 'Ammo Box Sniper', price = 21},
{name = 'boxflare', label = 'Ammo Box Flare', price = 10},
